[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
script = "script"

solc_version = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

verbosity = 3
fuzz_runs = 256
fuzz_max_test_rejects = 65536

gas_reports = ["*"]

line_length = 120
tab_width = 4
bracket_spacing = true

extra_output = ["abi"]
extra_output_files = ["abi"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
